### ISSUE TITLE
Pilot-Spark Script not the same as Spark

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/midas#6]
Hi Giannis,
I just looked at your commit e5abc96db0fff85f265dd4f21b5d6c72f1801ad3

I think the reason for the inconsistent behavior is the way you initialize the SparkContext:
```
Spark/PilotSparkSingleNodeTh.py
     sc = SparkContext(appName="ThroughputTest")
```
   => this starts a new local SparkContext and does not connect to your Spark cluster!
```
Spark/SparkSingleNodeTh.py
     conf = SparkConf().setAppName("SparkTest").setMaster("spark://%s:7077"%sys.argv[1])
     sc = SparkContext(conf=conf)
```
Can you setup the Spark script in a consistent way and redo the test, please?

Thanks,
Andre

**Comment by iparask** [comment]
```spark-submit``` ([here](https://github.com/radical-cybertools/midas/blob/master/Spark/PilotSparkSingleNodeTh.sh#L44)) creates a Spark Context or Spark configuration which are overwritten if a SparkContext odject is created?

In addition, if ```SparkSingleNodeTh``` is executed through a ```spark-submit```, the execution should be the same?

According to the documentation a SparkContext is needed to create RDDs. Do you happen to know why it is as you say?

**Comment by georgeha** [comment]
I have two points/questions
    In spark 2.0.2 they changed the variable $SPARK_MASTER_IP to $SPARK_MASTER_HOST, so you need to change that in the batch script.

   When spark starts a new SparkContext I thought that spark parses the spark.defaults configurations so, spark is going to use the spark master which is defined in that file. @drelu please correct me if I am wrong.

Best, 

George

**Comment by drelu** [comment]
Hi Giannis, can you double check in the logs/sparks web-ui to ensure that the right Spark cluster (the one setup by RP) is used. There must be something going wrong as the performance is dramatically worse.

**Comment by iparask** [comment]
Hello, I executed the same script, ```PilotSparkSingleNode.py```, with ```/bin/hostname``` instead of ```/bin/sleep```. All the log files have as output the name of the worker node and not the master, which shows that they are executed in the correct cluster.

I am currently running the same test with setting up the master in the python file and using ```spark-submit``` to execute

**Comment by iparask** [comment]
Please take a look at this [notebook](https://github.com/radical-experiments/midas_exps/blob/master/Spark/SparkContextCreationOverheads.ipynb)

**Comment by iparask** [comment]
Closing since it was resolved
